In [4]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv(r"depresdata\300_P~\300_P\features\300_OpenFace2.1.0_Pose_gaze_AUs.csv")
df.head()

,frame,timestamp,confidence,success,pose_Tx,pose_Ty,pose_Tz,pose_Rx,pose_Ry,pose_Rz,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0.000,0.98,1,69.5,37.7,576.8,0.221,0.036,-0.068,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,2,0.033,0.98,1,69.4,37.4,577.5,0.219,0.037,-0.067,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,3,0.067,0.98,1,69.4,37.3,576.7,0.223,0.039,-0.069,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4,0.100,0.98,1,69.3,37.3,576.5,0.225,0.039,-0.069,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,5,0.133,0.98,1,69.4,37.3,576.6,0.225,0.039,-0.070,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19458 entries, 0 to 19457
Data columns (total 53 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   frame         19458 non-null  int64
 1   timestamp     19458 non-null  float64
 2   confidence    19458 non-null  float64
 3   success       19458 non-null  int64
 4   pose_Tx       19458 non-null  float64
 5   pose_Ty       19458 non-null  float64
 6   pose_Tz       19458 non-null  float64
 7   pose_Rx       19458 non-null  float64
 8   pose_Ry       19458 non-null  float64
 9   pose_Rz       19458 non-null  float64
 10  gaze_0_x      19458 non-null  float64
 11  gaze_0_y      19458 non-null  float64
 12  gaze_0_z      19458 non-null  float64
 13  gaze_1_x      19458 non-null  float64
 14  gaze_1_y      19458 non-null  float64
 15  gaze_1_z      19458 non-null  float64
 16  gaze_angle_x  19458 non-null  float64
 17  gaze_angle_y  19458 non-null  float64
 18  AU01_r        19458 non-null  float64
 19  AU02_r        19458 non-null  float64
 20  AU04_r        19458 non-null  float64
 21  AU05_r        19458 non-null  float64
 22  AU06_r        19458 non-null  float64
 23  AU07_r        19458 non-null  float64
 24  AU09_r        19458 non-null  float64
 25  AU10_r        19458 non-null  float64
 26  AU12_r        19458 non-null  float64
 27  AU14_r        19458 non-null  float64
 28  AU15_r        19458 non-null  float64
 29  AU17_r        19458 non-null  float64
 30  AU20_r        19458 non-null  float64
 31  AU23_r        19458 non-null  float64
 32  AU25_r        19458 non-null  float64
 33  AU26_r        19458 non-null  float64
 34  AU45_r        19458 non-null  float64
 35  AU01_c        19458 non-null  float64
 36  AU02_c        19458 non-null  float64
 37  AU04_c        19458 non-null  float64
 38  AU05_c        19458 non-null  float64
 39  AU06_c        19458 non-null  float64
 40  AU07_c        19458 non-null  float64
 41  AU09_c        19458 non-null  float64
 42  AU10_c        19458 non-null  float64
 43  AU12_c        19458 non-null  float64
 44  AU14_c        19458 non-null  float64
 45  AU15_c        19458 non-null  float64
 46  AU17_c        19458 non-null  float64
 47  AU20_c        19458 non-null  float64
 48  AU23_c        19458 non-null  float64
 49  AU25_c        19458 non-null  float64
 50  AU26_c        19458 non-null  float64
 51  AU28_c        19458 non-null  float64
 52  AU45_c        19458 non-null  float64
dtypes: float64(51), int64(2)
memory usage: 7.9 MB

In [12]:
# Define empty dictionaries to store categorized AUs
brow_movements_r = []
eye_movements_r = []
nose_movements_r = []
mouth_movements_r = []
other_r = []

brow_movements_c = []
eye_movements_c = []
nose_movements_c = []
mouth_movements_c = []
other_c = []

# List of FACS categories (modify as needed)
facs_categories = {
    "AU01": "Brow Movements",
    "AU02": "Brow Movements",
    "AU04": "Brow Movements",
    "AU05": "Brow Movements",
    "AU06": "Eye Movements",
    "AU07": "Eye Movements",
    "AU09": "Nose Movements",
    "AU10": "Mouth Movements",  # Assuming mouth movements for AU10 based on limited data
    "AU12": "Mouth Movements",
    "AU14": "Mouth Movements",
    "AU15": "Mouth Movements",
    "AU17": "Mouth Movements",
    "AU20": "Mouth Movements",
    "AU23": "Other",
    "AU25": "Other",
    "AU26": "Other",
    "AU28": "Other",  # Assuming AU28 belongs to Other category (verify its definition)
    "AU45": "Other",
}

# Initialize empty dictionaries to store categorized AUs
brow_movements = []
eye_movements = []
nose_movements = []
mouth_movements = []
other = []

au_data = df.columns.tolist()

# Loop through each AU data point
for au in au_data:
  category = facs_categories.get(au[:-2])  # Extract category based on AU code (remove "_r" or "_c")
  if category == "Brow Movements":
    brow_movements.append(au)
  elif category == "Eye Movements":
    eye_movements.append(au)
  elif category == "Nose Movements":
    nose_movements.append(au)
  elif category == "Mouth Movements":
    mouth_movements.append(au)
  else:
    other.append(au)  # Handle uncategorized AUs or missing categories

# Print the categorized AUs (modify as needed)
print("Brow Movements:")
print(brow_movements)

print("\nEye Movements:")
print(eye_movements)

print("\nNose Movements:")
print(nose_movements)

print("\nMouth Movements:")
print(mouth_movements)

Brow Movements:
['AU01_r', 'AU02_r', 'AU04_r', 'AU05_r', 'AU01_c', 'AU02_c', 'AU04_c', 'AU05_c']

Eye Movements:
['AU06_r', 'AU07_r', 'AU06_c', 'AU07_c']

Nose Movements:
['AU09_r', 'AU09_c']

Mouth Movements:
['AU10_r', 'AU12_r', 'AU14_r', 'AU15_r', 'AU17_r', 'AU20_r', 'AU10_c', 'AU12_c', 'AU14_c', 'AU15_c', 'AU17_c', 'AU20_c']